### ISSUE TITLE
1/30 notes

### ISSUE THREAD

**Issue by huckiyang** [virginiakm1988/LogME-CTC#2]
@virginiakm1988 it seems directly use imagenet pre-training to reshape will take many eng time. 

just consider to use AST to tune it if you are not familiar with TF (since a lot pre-trained acoustic models are still TF based)

- use the audioset pre-trained 
https://github.com/huckiyang/speech2music/blob/main/ast_update_2022_for_amy.py

**Comment by virginiakm1988** [comment]
@huckiyang 
updates on this issue
1. I have done setting up the env and have ran ast successfully. There's still some minor bugs to be fixed(convert melspectrogram back to spectrogram since the input of ast model should be spectrogram/ reduce the batch size). Hopefully I can fix them tomorrow before out meeting.
2. Just wanna to make sure if im correct, i think the feature for LogME should be the x here (https://github.com/YuanGongND/ast/blob/master/src/models/ast_models.py#L184)?
3. For cross modal examination, can the pretrained model also be obtained by this repo? Since ast_models provides imageNet pretrained models.
It seems that cifar10 pretrained checkpoints could be obtained in huggingface, but not sure if there are mnist or cifar10 pretrained checkpoints in timm, which is used in the ast model. will try this tomorrow as well.
https://huggingface.co/nateraw/vit-base-patch16-224-cifar10

**Comment by huckiyang** [comment]
@virginiakm1988 

> 1. I have done setting up the env and have ran ast successfully. There's still some minor bugs to be fixed(convert melspectrogram back to spectrogram since the input of ast model should be spectrogram/ reduce the batch size). Hopefully I can fix them tomorrow before out meeting.

- sure thanks

> 2. Just wanna to make sure if im correct, i think the feature for LogME should be the x here (https://github.com/YuanGongND/ast/blob/master/src/models/ast_models.py#L184)?

- good question, I think you are correct. the L186 is make it for patch-wise format. (https://github.com/YuanGongND/ast/blob/9e3bd9942210680b833b08c39d09f2284ddc4d1d/src/models/ast_models.py#L72)

> 3. For cross modal examination, can the pretrained model also be obtained by this repo? Since ast_models provides imageNet pretrained models.
>    It seems that cifar10 pretrained checkpoints could be obtained in huggingface, but not sure if there are mnist or cifar10 pretrained checkpoints in timm, which is used in the ast model. will try this tomorrow as well.
>    https://huggingface.co/nateraw/vit-base-patch16-224-cifar10

- It is possible but I am not sure how much it is worthy. If you can finish in 2~3 days, it is good to try. 

Remember to save all the features of each evaluated model in your logme exp. I
These could be a good toy sample to the community for future study
